# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AukzjhLivY6oMz4zgLZNpF7x9EJ0wFTw
"""



a = "Hello\nworld"
print(a)
print(len(a))
print(a[6])
print(a[0])
print(a[0]+a[8]+a[5]+a[-1]+a[-3])

name = "sam"
b = "P"+name[1:]
print(b)

a = "Essa é uma string"
b = a.split("a")
print(b)
#print(b[2])

a = "Essa é uma mensagem: {} {} {}"
msg0 = "Aviso 0"
msg1 = "Aviso 1"
msg2 = "Aviso 2"
print(a.format(msg0,msg1,msg2))

a = "abcdefghijk"
print(a[2:])
print(a[6:10])
print(a[::2])
print(a[::3])
print(a[2:7:2])
print(a[::-1])

nome = "Carolina"
print(f"O nome dela é {nome}")
matricula = 123456
print(f"O nome dela é {nome} e a matricula é {matricula}")